// ---------------------------------------------------------
// Nostra – shared data (Updated with matching product images)
// Every page reads from this single source of truth.
// ---------------------------------------------------------

const PRODUCTS = [
  // ---- New Arrivals ----
  {
    id: "p1",
    name: "Floral Weekend Shirt",
    price: 799,
    oldPrice: null,
    rating: 4,
    section: "new-arrival",
    arrival: "new",
    occasion: ["casual"],
    color: ["white", "green"],
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "A lightweight cotton-blend shirt printed with a hand-painted floral motif. Relaxed fit with a soft collar that layers well over a tee."
  },
  {
    id: "p2",
    name: "Tailored Trousers",
    price: 899,
    oldPrice: null,
    rating: 4,
    section: "new-arrival",
    arrival: "new",
    occasion: ["formal"],
    color: ["white"],
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "Sharp, straight-leg trousers in a breathable weave — built for the office and easy to dress down after hours."
  },
  {
    id: "p3",
    name: "Denim Overshirt",
    price: 999,
    oldPrice: null,
    rating: 3,
    section: "new-arrival",
    arrival: "new",
    occasion: ["casual"],
    color: ["blue"],
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "A mid-weight denim overshirt with a boxy silhouette and dual chest pockets. Layer it open over plain tees."
  },
  {
    id: "p4",
    name: "Field Jacket",
    price: 1299,
    oldPrice: null,
    rating: 5,
    section: "new-arrival",
    arrival: "new",
    occasion: ["formal"],
    color: ["white"],
    image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "A utilitarian field jacket with four flap pockets and a corozo-button placket, finished in brushed cotton twill."
  },

  // ---- Most Wanted ----
  {
    id: "p5",
    name: "Ash Grey Hoodie",
    price: 899,
    oldPrice: 1199,
    rating: 4,
    section: "most-wanted",
    arrival: "old",
    occasion: ["casual"],
    color: ["white"],
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "Brushed fleece hoodie in ash grey with a kangaroo pocket — soft, roomy, and built for everyday wear."
  },
  {
    id: "p6",
    name: "Cargo Joggers",
    price: 799,
    oldPrice: 999,
    rating: 3,
    section: "most-wanted",
    arrival: "old",
    occasion: ["casual"],
    color: ["green"],
    image: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "Tapered cargo joggers with utility pockets and an elastic cuff — comfortable enough for all-day wear."
  },
  {
    id: "p7",
    name: "Utility Pullover",
    price: 949,
    oldPrice: 1199,
    rating: 4,
    section: "most-wanted",
    arrival: "old",
    occasion: ["casual"],
    color: ["green", "white"],
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "A half-zip utility pullover in a heavyweight cotton blend, with a chest pocket and ribbed cuffs."
  },
  {
    id: "p8",
    name: "Bomber Jacket",
    price: 1499,
    oldPrice: 1899,
    rating: 5,
    section: "most-wanted",
    arrival: "old",
    occasion: ["formal"],
    color: ["blue"],
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "A classic bomber cut in a soft-touch shell, ribbed hem and cuffs, fully lined for cooler evenings."
  },
  {
    id: "p9",
    name: "Graphic Tee",
    price: 499,
    oldPrice: 699,
    rating: 3,
    section: "most-wanted",
    arrival: "old",
    occasion: ["casual"],
    color: ["white"],
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "100% cotton tee with a subtle front print — the everyday staple that layers under anything."
  },
  {
    id: "p10",
    name: "Zip Hoodie",
    price: 999,
    oldPrice: 1299,
    rating: 4,
    section: "most-wanted",
    arrival: "old",
    occasion: ["casual"],
    color: ["blue"],
    image: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "Full-zip hoodie in brushed fleece with a two-way zip and dropped shoulder seams."
  },
  {
    id: "p11",
    name: "Block Print Shirt",
    price: 849,
    oldPrice: 1099,
    rating: 4,
    section: "most-wanted",
    arrival: "old",
    occasion: ["formal"],
    color: ["red", "white"],
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "Short-sleeve shirt in a hand block-print pattern, cut for a relaxed camp-collar fit."
  },
  {
    id: "p12",
    name: "Knit Sweater",
    price: 1099,
    oldPrice: 1399,
    rating: 5,
    section: "most-wanted",
    arrival: "old",
    occasion: ["formal"],
    color: ["green"],
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&auto=format&fit=crop&q=80",
    badge: "sale",
    description: "A fine-gauge merino-blend sweater with a crew neck — dresses up or down with equal ease."
  },

  // ---- Collection extras ----
  {
    id: "p13",
    name: "Beach Print Shirt",
    price: 749,
    oldPrice: null,
    rating: 4,
    section: "collection",
    arrival: "new",
    occasion: ["beach"],
    color: ["blue", "white"],
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "Loose, breathable and quick-drying — designed for salt air and long afternoons by the water."
  },
  {
    id: "p14",
    name: "Coastal Stripe Shirt",
    price: 699,
    oldPrice: null,
    rating: 4,
    section: "collection",
    arrival: "old",
    occasion: ["beach"],
    color: ["blue", "white"],
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "Fine vertical stripes on a soft cotton-linen blend, cut with a relaxed body and short sleeve."
  },
  {
    id: "p15",
    name: "Classic White Shirt",
    price: 699,
    oldPrice: null,
    rating: 5,
    section: "collection",
    arrival: "new",
    occasion: ["formal"],
    color: ["white"],
    image: "https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "A wardrobe staple woven from brushed oxford cotton, tailored with a clean point collar."
  },
  {
    id: "p16",
    name: "Rusty Brown Overshirt",
    price: 899,
    oldPrice: null,
    rating: 3,
    section: "collection",
    arrival: "old",
    occasion: ["casual"],
    color: ["red", "white"],
    image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "An unlined overshirt in a heavy cotton canvas, patch pockets front and back."
  },
  {
    id: "p17",
    name: "Party Floral Shirt",
    price: 599,
    oldPrice: null,
    rating: 5,
    section: "collection",
    arrival: "new",
    occasion: ["formal"],
    color: ["red"],
    image: "https://images.unsplash.com/photo-1589571894960-20bbe2828d1b?w=500&auto=format&fit=crop&q=80",
    badge: null,
    description: "A statement short-sleeve shirt in a bold floral print — the one to reach for when the occasion calls for more."
  }
];
